### PR TITLE
Build libnanomsg during gem install

### PR DESCRIPTION
**Pull request by aw**
Hi,

I thought it would be convenient if the `libnanomsg` C extension could be built during `bundle install` or `gem install`.

I also slightly updated the documentation :palm_tree:

### CODE REVIEW

**Comment by aw** [comment]
... let me fix these tests first ;)

**Comment by chuckremes** [comment]
Let me know if/when you are ready and I’ll merge it in.

**Comment by aw** [comment]
Oh sorry, yes the tests pass.
Thanks!

**Comment by chuckremes** [comment]
Thank you for this contribution! Would you like to be added to the project as a collaborator? I don't spend much time with nanomsg anymore...

**Comment by aw** [comment]
No, that's not necessary. Thanks.

**Pull request merged**
